name: localstack

services:
  localstack:
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    container_name: "localstack"
    env_file:
      - secrets.env
    volumes:
      - "localstack:/var/lib/localstack"
      # Won't work with User-installed docker socket
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack:
    name: localstack
